# Generated by Django 2.2.1 on 2020-10-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre del laboratorio')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='TipoPresentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopresentacion', models.CharField(max_length=20, unique=True, verbose_name='Tipo de Presentacion')),
            ],
            options={
                'verbose_name': 'Tipo Presentacion',
                'verbose_name_plural': 'Tipo de Presentacion',
                'db_table': 'tipopresentacion',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.PositiveIntegerField(default='', verbose_name='Numero de estante')),
                ('fila', models.PositiveIntegerField(default='', verbose_name='Numero de fila')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('existencia', models.PositiveIntegerField(default=0, verbose_name='Existencia')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Laboratorio')),
                ('tipopresentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.TipoPresentacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroloteproducto', models.PositiveIntegerField(verbose_name='Numero de lote del producto')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('preciocompra', models.FloatField(default=0, verbose_name='Precio del costo')),
                ('precioventa', models.FloatField(default=0, verbose_name='Precio venta')),
                ('fechavencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fechacompra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elproducto', to='producto.Producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Ubicacion')),
            ],
            options={
                'verbose_name': 'Detalle producto',
                'verbose_name_plural': 'Detalle de productos',
                'db_table': 'detalleproducto',
            },
        ),
    ]
