# Generated by Django 2.2.1 on 2020-10-06 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('total', models.FloatField(blank=True, default=0.0, verbose_name='total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
            options={
                'verbose_name': 'Comprobante Compra',
                'verbose_name_plural': 'Comprobante de Compra',
                'db_table': 'comprobantecompra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroloteproducto', models.PositiveIntegerField(verbose_name='Numero de lote del producto')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fechavencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('preciocompra', models.FloatField(default=0, verbose_name='Precio del costo')),
                ('precioventa', models.FloatField(default=0, verbose_name='Precio venta')),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True, verbose_name='subtotal')),
                ('comprobantecompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetalleCompra', to='compra.ComprobanteCompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Ubicacion')),
            ],
            options={
                'verbose_name': 'Detalle compra',
                'verbose_name_plural': 'Detalle de compras',
                'db_table': 'detallecompra',
            },
        ),
    ]
