# Generated by Django 2.2.1 on 2020-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20201006_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='numeroloteproducto',
            field=models.CharField(max_length=50, verbose_name='Numero de lote del producto'),
        ),
    ]
