# Generated by Django 2.2.1 on 2020-10-06 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='total')),
                ('efectivo', models.FloatField(blank=True, default=0, null=True, verbose_name='efectivo')),
                ('vuelto', models.FloatField(blank=True, default=0, null=True, verbose_name='vuelto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Empleado')),
            ],
            options={
                'verbose_name': 'Comprobante Venta',
                'verbose_name_plural': 'Comprobante de Venta',
                'db_table': 'comprobanteventa',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerolote', models.CharField(max_length=10, verbose_name='Numero de lote')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True, verbose_name='subtotal')),
                ('comprobanteventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Detalle', to='venta.ComprobanteVenta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
            options={
                'verbose_name': 'Detalle venta',
                'verbose_name_plural': 'Detalle de ventas',
                'db_table': 'detalleventa',
            },
        ),
    ]
