# Generated by Django 2.2.1 on 2020-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='numerolote',
            field=models.CharField(max_length=50, verbose_name='Numero de lote'),
        ),
    ]
